import axios from "axios";
import { v4 as uuid } from "uuid";
import { isMongoReady } from "../config/database.js";
import { db } from "../data/store.js";
import { CropPrediction } from "../models/CropPrediction.js";
import { DiseaseDetection } from "../models/DiseaseDetection.js";

const FLASK_API_BASE_URL = process.env.FLASK_API_URL || "http://localhost:5000";

function normalizePayload(payload) {
    return {
        N: Number(payload.N),
        P: Number(payload.P),
        K: Number(payload.K),
        temperature: Number(payload.temperature),
        humidity: Number(payload.humidity),
        ph: Number(payload.ph),
        rainfall: Number(payload.rainfall),
        location: String(payload.location || "").trim(),
        season: String(payload.season || "").trim(),
        soil: String(payload.soil || "").trim(),
    };
}

export async function createPrediction(payload) {
    const input = normalizePayload(payload);

    console.log("Crop prediction request received:", input);

    let flaskResponse;
    try {
        flaskResponse = await axios.post(`${FLASK_API_BASE_URL}/predict`, input, {
            timeout: 15000,
            headers: {
                "Content-Type": "application/json",
            },
        });
    } catch (error) {
        if (error.response) {
            const message = error.response.data?.error || "Flask service returned an error";
            const wrappedError = new Error(message);
            wrappedError.status = error.response.status;
            throw wrappedError;
        }

        if (error.request) {
            const wrappedError = new Error("Flask service is not reachable");
            wrappedError.status = 502;
            throw wrappedError;
        }

        const wrappedError = new Error(error.message || "Failed to call Flask service");
        wrappedError.status = 500;
        throw wrappedError;
    }

    console.log("Flask prediction response:", flaskResponse.data);

    const recommendations = Array.isArray(flaskResponse.data?.recommendations)
        ? flaskResponse.data.recommendations
        : [];
    const explanation = flaskResponse.data?.explanation || "Recommendation generated by Flask ML service.";

    if (isMongoReady()) {
        await CropPrediction.create({ input, recommendations, explanation });
    } else {
        db.cropPredictions.push({
            id: uuid(),
            input,
            recommendations,
            explanation,
            createdAt: new Date().toISOString(),
        });
    }

    return flaskResponse.data;
}

export async function detectDiseaseFromImage(file) {
    const result = {
        disease: "Leaf Blight",
        confidence: 0.91,
        severity: "Medium",
        treatment: {
            pesticide: "Copper Oxychloride",
            dosage: "2g per liter of water",
            frequency: "Apply every 7 days for 3 cycles",
        },
        prevention: [
            "Remove infected leaves early",
            "Avoid overhead irrigation in late evening",
            "Use disease-resistant varieties when possible",
        ],
    };

    if (isMongoReady()) {
        await DiseaseDetection.create({
            fileName: file?.originalname || "image.jpg",
            mimeType: file?.mimetype || "image/jpeg",
            size: file?.size || 0,
            ...result,
        });
    } else {
        db.diseaseDetections.push({
            id: uuid(),
            fileName: file?.originalname || "image.jpg",
            mimeType: file?.mimetype || "image/jpeg",
            size: file?.size || 0,
            ...result,
            createdAt: new Date().toISOString(),
        });
    }

    return result;
}
