import axios from "axios";
import FormData from "form-data";
import { v4 as uuid } from "uuid";
import { isMongoReady } from "../config/database.js";
import { db } from "../data/store.js";
import { CropPrediction } from "../models/CropPrediction.js";
import { DiseaseDetection } from "../models/DiseaseDetection.js";

const FLASK_API_BASE_URL = process.env.FLASK_API_URL || "http://localhost:5000";
const DISEASE_FLASK_API_BASE_URL =
    process.env.DISEASE_FLASK_API_URL || "http://localhost:5002";

function normalizePayload(payload) {
    return {
        N: Number(payload.N),
        P: Number(payload.P),
        K: Number(payload.K),
        temperature: Number(payload.temperature),
        humidity: Number(payload.humidity),
        ph: Number(payload.ph),
        rainfall: Number(payload.rainfall),
        location: String(payload.location || "").trim(),
        season: String(payload.season || "").trim(),
        soil: String(payload.soil || "").trim(),
    };
}

export async function createPrediction(payload) {
    const input = normalizePayload(payload);

    console.log("Crop prediction request received:", input);

    let flaskResponse;
    try {
        flaskResponse = await axios.post(`${FLASK_API_BASE_URL}/predict`, input, {
            timeout: 15000,
            headers: {
                "Content-Type": "application/json",
            },
        });
    } catch (error) {
        if (error.response) {
            const message = error.response.data?.error || "Flask service returned an error";
            const wrappedError = new Error(message);
            wrappedError.status = error.response.status;
            throw wrappedError;
        }

        if (error.request) {
            const wrappedError = new Error("Flask service is not reachable");
            wrappedError.status = 502;
            throw wrappedError;
        }

        const wrappedError = new Error(error.message || "Failed to call Flask service");
        wrappedError.status = 500;
        throw wrappedError;
    }

    console.log("Flask prediction response:", flaskResponse.data);

    const recommendations = Array.isArray(flaskResponse.data?.recommendations)
        ? flaskResponse.data.recommendations
        : [];
    const explanation = flaskResponse.data?.explanation || "Recommendation generated by Flask ML service.";

    if (isMongoReady()) {
        await CropPrediction.create({ input, recommendations, explanation });
    } else {
        db.cropPredictions.push({
            id: uuid(),
            input,
            recommendations,
            explanation,
            createdAt: new Date().toISOString(),
        });
    }

    return flaskResponse.data;
}

export async function createOcrPredictionFromImage(file, payload = {}) {
    console.log("Crop OCR request received:", {
        fileName: file?.originalname || "",
        mimeType: file?.mimetype || "",
        size: file?.size || 0,
        location: payload?.location || "",
        season: payload?.season || "",
        soil: payload?.soil || "",
    });

    const form = new FormData();
    form.append("file", file.buffer, {
        filename: file.originalname || "soil-report.jpg",
        contentType: file.mimetype || "image/jpeg",
        knownLength: file.size || undefined,
    });

    if (payload.location) {
        form.append("location", String(payload.location));
    }
    if (payload.season) {
        form.append("season", String(payload.season));
    }
    if (payload.soil) {
        form.append("soil", String(payload.soil));
    }

    let flaskResponse;
    try {
        flaskResponse = await axios.post(`${FLASK_API_BASE_URL}/ocr-predict`, form, {
            timeout: 30000,
            headers: form.getHeaders(),
            maxBodyLength: Infinity,
            maxContentLength: Infinity,
        });
    } catch (error) {
        if (error.response) {
            const message = error.response.data?.error || "Flask OCR service returned an error";
            const wrappedError = new Error(message);
            wrappedError.status = error.response.status;
            wrappedError.details = error.response.data?.details || null;
            throw wrappedError;
        }

        if (error.request) {
            const wrappedError = new Error("Flask OCR service is not reachable");
            wrappedError.status = 502;
            throw wrappedError;
        }

        const wrappedError = new Error(error.message || "Failed to call Flask OCR service");
        wrappedError.status = 500;
        throw wrappedError;
    }

    console.log("Flask OCR response:", flaskResponse.data);

    const result = flaskResponse.data;
    const extracted = result?.extracted || {};
    const recommendations = Array.isArray(result?.recommendations) ? result.recommendations : [];
    const explanation = result?.explanation || "Recommendation generated from OCR-extracted report values.";

    if (recommendations.length > 0) {
        const input = {
            N: Number(extracted.N),
            P: Number(extracted.P),
            K: Number(extracted.K),
            temperature: Number(extracted.temperature),
            humidity: Number(extracted.humidity),
            ph: Number(extracted.ph),
            rainfall: Number(extracted.rainfall),
            location: String(result?.context?.location || payload.location || "").trim(),
            season: String(result?.context?.season || payload.season || "").trim(),
            soil: String(result?.context?.soil || payload.soil || "").trim(),
        };

        if (isMongoReady()) {
            await CropPrediction.create({ input, recommendations, explanation });
        } else {
            db.cropPredictions.push({
                id: uuid(),
                input,
                recommendations,
                explanation,
                createdAt: new Date().toISOString(),
            });
        }
    }

    return result;
}

export async function detectDiseaseFromImage(file) {
    console.log("Disease detection request received:", {
        fileName: file?.originalname || "",
        mimeType: file?.mimetype || "",
        size: file?.size || 0,
    });

    const form = new FormData();
    form.append("file", file.buffer, {
        filename: file.originalname || "image.jpg",
        contentType: file.mimetype || "image/jpeg",
        knownLength: file.size || undefined,
    });

    let flaskResponse;
    try {
        flaskResponse = await axios.post(
            `${DISEASE_FLASK_API_BASE_URL}/predict`,
            form,
            {
                timeout: 30000,
                headers: form.getHeaders(),
                maxBodyLength: Infinity,
                maxContentLength: Infinity,
            },
        );
    } catch (error) {
        if (error.response) {
            const message = error.response.data?.error || "Flask service returned an error";
            const wrappedError = new Error(message);
            wrappedError.status = error.response.status;
            wrappedError.details = error.response.data?.details || null;
            throw wrappedError;
        }

        if (error.request) {
            const wrappedError = new Error("Flask disease service is not reachable");
            wrappedError.status = 502;
            throw wrappedError;
        }

        const wrappedError = new Error(error.message || "Failed to call Flask disease service");
        wrappedError.status = 500;
        throw wrappedError;
    }

    console.log("Flask disease response:", flaskResponse.data);

    const result = flaskResponse.data;

    if (isMongoReady()) {
        await DiseaseDetection.create({
            fileName: file?.originalname || "image.jpg",
            mimeType: file?.mimetype || "image/jpeg",
            size: file?.size || 0,
            disease: String(result?.disease || ""),
            confidence: Number(result?.confidence || 0),
            treatment: result?.treatment || undefined,
            prevention: Array.isArray(result?.prevention) ? result.prevention : [],
        });
    } else {
        db.diseaseDetections.push({
            id: uuid(),
            fileName: file?.originalname || "image.jpg",
            mimeType: file?.mimetype || "image/jpeg",
            size: file?.size || 0,
            disease: String(result?.disease || ""),
            confidence: Number(result?.confidence || 0),
            treatment: result?.treatment || null,
            prevention: Array.isArray(result?.prevention) ? result.prevention : [],
            createdAt: new Date().toISOString(),
        });
    }

    return result;
}
