import axios from "axios";
import FormData from "form-data";
import { v4 as uuid } from "uuid";
import { isMongoReady } from "../config/database.js";
import { db } from "../data/store.js";
import { CropPrediction } from "../models/CropPrediction.js";
import { DiseaseDetection } from "../models/DiseaseDetection.js";

const FLASK_API_BASE_URL = process.env.FLASK_API_URL || "http://localhost:5000";
const DISEASE_FLASK_API_BASE_URL =
    process.env.DISEASE_FLASK_API_URL || "http://localhost:5002";

function normalizePayload(payload) {
    return {
        N: Number(payload.N),
        P: Number(payload.P),
        K: Number(payload.K),
        temperature: Number(payload.temperature),
        humidity: Number(payload.humidity),
        ph: Number(payload.ph),
        rainfall: Number(payload.rainfall),
        location: String(payload.location || "").trim(),
        season: String(payload.season || "").trim(),
        soil: String(payload.soil || "").trim(),
    };
}

export async function createPrediction(payload) {
    const input = normalizePayload(payload);

    console.log("Crop prediction request received:", input);

    let flaskResponse;
    try {
        flaskResponse = await axios.post(`${FLASK_API_BASE_URL}/predict`, input, {
            timeout: 15000,
            headers: {
                "Content-Type": "application/json",
            },
        });
    } catch (error) {
        if (error.response) {
            const message = error.response.data?.error || "Flask service returned an error";
            const wrappedError = new Error(message);
            wrappedError.status = error.response.status;
            throw wrappedError;
        }

        if (error.request) {
            const wrappedError = new Error("Flask service is not reachable");
            wrappedError.status = 502;
            throw wrappedError;
        }

        const wrappedError = new Error(error.message || "Failed to call Flask service");
        wrappedError.status = 500;
        throw wrappedError;
    }

    console.log("Flask prediction response:", flaskResponse.data);

    const recommendations = Array.isArray(flaskResponse.data?.recommendations)
        ? flaskResponse.data.recommendations
        : [];
    const explanation = flaskResponse.data?.explanation || "Recommendation generated by Flask ML service.";

    if (isMongoReady()) {
        await CropPrediction.create({ input, recommendations, explanation });
    } else {
        db.cropPredictions.push({
            id: uuid(),
            input,
            recommendations,
            explanation,
            createdAt: new Date().toISOString(),
        });
    }

    return flaskResponse.data;
}

export async function detectDiseaseFromImage(file) {
    console.log("Disease detection request received:", {
        fileName: file?.originalname || "",
        mimeType: file?.mimetype || "",
        size: file?.size || 0,
    });

    const form = new FormData();
    form.append("file", file.buffer, {
        filename: file.originalname || "image.jpg",
        contentType: file.mimetype || "image/jpeg",
        knownLength: file.size || undefined,
    });

    let flaskResponse;
    try {
        flaskResponse = await axios.post(
            `${DISEASE_FLASK_API_BASE_URL}/predict`,
            form,
            {
                timeout: 30000,
                headers: form.getHeaders(),
                maxBodyLength: Infinity,
                maxContentLength: Infinity,
            },
        );
    } catch (error) {
        if (error.response) {
            const message = error.response.data?.error || "Flask service returned an error";
            const wrappedError = new Error(message);
            wrappedError.status = error.response.status;
            wrappedError.details = error.response.data?.details || null;
            throw wrappedError;
        }

        if (error.request) {
            const wrappedError = new Error("Flask disease service is not reachable");
            wrappedError.status = 502;
            throw wrappedError;
        }

        const wrappedError = new Error(error.message || "Failed to call Flask disease service");
        wrappedError.status = 500;
        throw wrappedError;
    }

    console.log("Flask disease response:", flaskResponse.data);

    const result = {
        disease: String(flaskResponse.data?.disease || ""),
        confidence: Number(flaskResponse.data?.confidence || 0),
    };

    if (isMongoReady()) {
        await DiseaseDetection.create({
            fileName: file?.originalname || "image.jpg",
            mimeType: file?.mimetype || "image/jpeg",
            size: file?.size || 0,
            ...result,
        });
    } else {
        db.diseaseDetections.push({
            id: uuid(),
            fileName: file?.originalname || "image.jpg",
            mimeType: file?.mimetype || "image/jpeg",
            size: file?.size || 0,
            ...result,
            createdAt: new Date().toISOString(),
        });
    }

    return result;
}
